import { useMemo, useState } from "react";

const SunswiftDetails = () => {
  const carouselImages = [
    { src: "/assets/sunswift/top.png" },
    { src: "/assets/sunswift/mid1.png" },
    { src: "/assets/sunswift/mid2.png" },
    { src: "/assets/sunswift/bottom.png" },
  ];
  const [activeIndex, setActiveIndex] = useState(0);
  const lastIndex = carouselImages.length - 1;
  const slides = useMemo(() => carouselImages, [carouselImages]);
  const currentIndex = carouselImages.length === 0 ? 0 : activeIndex;

  const handlePrev = () => {
    setActiveIndex((prev) => Math.max(prev - 1, 0));
  };

  const handleNext = () => {
    setActiveIndex((prev) => Math.min(prev + 1, lastIndex));
  };

  return (
    <section className="project-detail">
      <p>
        The{" "}
        <a href="https://www.sunswift.com/" target="_blank" rel="noreferrer" className="text-link">
          Sunswift Racing
        </a>{" "}
        electric vehicle is an innovative project developed by a team of students from the
        University of New South Wales (UNSW). This vehicle not only set a{" "}
        <a
          href="https://www.unsw.edu.au/newsroom/news/2022/10/ev-record-breakers-sunswift-7-goes-1000km-on-a-single-charge-in-worlds-best-time"
          target="_blank"
          rel="noreferrer"
          className="text-link"
        >
          Guinness World Record
        </a>{" "}
        in 2022 but also won the{" "}
        <a
          href="https://newsroom.unsw.edu.au/news/science-tech/unsw-sunswift-racing-claims-bridgestone-world-solar-challenge-victory-after-wind"
          target="_blank"
          rel="noreferrer"
          className="text-link"
        >
          2023 Bridgestone World Solar Challenge
        </a>, showcasing the incredible capabilities of solar-powered vehicles.
      </p>

      <div className="hover-container">
        <img src="/assets/sunswift/sr7-1.jpg" className="image-ps2-1" />
      </div>

      <h3>My Role</h3>

      <p>
        As the Project Lead for the Energy Systems Department, I was responsible for overseeing the
        development of the Maximum Power Point Tracking (MPPT) system. MPPT is a system that
        dynamically tracks and maximizes the power output from solar panels by adjusting their
        electrical operating point with changes in sunlight or temperature, playing a major role in
        the vehicle's performance and energy efficiency. This technology was crucial in optimizing
        the energy generated by the solar panels, ensuring that the vehicle could operate at peak
        efficiency throughout the race. My role involved leading the MPPT project, integrating it
        into the vehicle's energy control system, and ensuring that it maximized the energy
        efficiency of the solar panels.
      </p>

      <div className="hover-container">
        <img src="/assets/sunswift/team.jpg" className="image-pe1-1" />
      </div>

      <h3>MPPT PCB</h3>

      <p>
        The MPPT PCB board features an isolated H-bridge boost converter and an STM32
        microcontroller, designed to execute the dynamic tracking algorithm. The H-bridge boost
        converter efficiently adjusts the voltage to match the optimal power point of the solar
        panels, while the STM32 microcontroller handles the real-time calculations
        and decision-making for tracking changes in sunlight and temperature. This is a mixed-signal
        design, combining analogue current sensing with digital microcontroller circuitry along with
        switching power electronics. Separate grounding techniques are used to minimize noise
        interference between the analogue and digital sections, ensuring accurate measurements and
        stable operation.
      </p>

      <div className="hover-container">
        <img src="/assets/sunswift/3d.png" className="image-pe1-1" />
      </div>

      <p>
        This is a 4-layer PCB designed in Altium Designer, capable of supplying up
        to 1kW of power to the load. The design uses separate grounding techniques to minimize noise
        interference between the analogue and digital sections, ensuring accurate measurements and
        stable operation. The board's 4-layer structure improves power delivery and signal integrity
        by dedicating one layer to the power plane and another to the ground plane, reducing voltage
        ripple and ensuring stable operation under high load conditions. The outer layers handle
        signal routing and component placement, while the inner layers provide a low-impedance path
        for both power and ground, crucial for maintaining performance in high-power applications.
      </p>

      <div className="image-carousel" aria-label="MPPT PCB carousel">
        <div
          className="carousel-track"
          style={{
            transform: `translateX(-${activeIndex * 100}%)`,
            transition: "transform 0.35s ease",
          }}
        >
          {slides.map((image) => (
            <div key={image.src} className="carousel-slide">
              <img src={image.src} />
            </div>
          ))}
        </div>

        <button
          className="carousel-button left"
          aria-label="Previous Image"
          onClick={handlePrev}
          type="button"
          disabled={activeIndex === 0}
        >
          &#10094;
        </button>
        <button
          className="carousel-button right"
          aria-label="Next Image"
          onClick={handleNext}
          type="button"
          disabled={activeIndex === lastIndex}
        >
          &#10095;
        </button>
      </div>
      <div className="carousel-dots">
        {carouselImages.map((_, index) => (
          <button
            key={`sunswift-dot-${index}`}
            type="button"
            className={`carousel-dot ${index === currentIndex ? "active" : ""}`}
            onClick={() => setActiveIndex(index)}
            aria-label={`Go to slide ${index + 1}`}
            aria-pressed={index === currentIndex}
          />
        ))}
      </div>

      <p>
        I have attached the full schematic diagram and the Altium Draftsman files below, which
        include detailed layout designs, component annotations, BOM, layer stack management, and
        more.
      </p>

      <div className="pdf-container">
        <a
          href="/assets/sunswift/MPPT_V1_Schematic.pdf"
          target="_blank"
          rel="noopener noreferrer"
          className="pdf-link"
        >
          Schematic Download
        </a>
      </div>

      <div className="pdf-container">
        <a
          href="/assets/sunswift/MPPT_V1_Draftsman.pdf"
          target="_blank"
          rel="noopener noreferrer"
          className="pdf-link"
        >
          Draftsman Download
        </a>
      </div>
    </section>
  );
};

export default SunswiftDetails;
